# intentlink-backend/test_eip712_consistency.py
"""
Test to verify EIP-712 hash consistency between frontend signing and backend verification.
This test ensures that the signature generated by signing matches what the backend verifies.
"""

from eth_account import Account
from eth_account.messages import encode_typed_data
from services.signature_service import signature_service
from web3 import Web3
import sys

def test_eip712_hash_consistency():
    """
    Verify that the EIP-712 hash generated for signing matches
    the hash used for verification.
    """
    print("="*70)
    print("TESTING EIP-712 HASH CONSISTENCY")
    print("="*70)
    
    chain_id = 1043
    plan_id_hex = "0xbf35a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0"
    plan_hash_hex = "0xa1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2"
    nonce = 0
    
    print(f"Test Parameters:")
    print(f"  Chain ID: {chain_id}")
    print(f"  Plan ID:  {plan_id_hex}")
    print(f"  Plan Hash: {plan_hash_hex}")
    print(f"  Nonce: {nonce}")
    print()
    
    # Generate typed data (what frontend receives)
    print("Step 1: Generating typed data (simulating backend /prepare endpoint)...")
    typed_data = signature_service.generate_typed_data(
        chain_id, plan_id_hex, plan_hash_hex, nonce
    )
    
    # Extract expiry from generated data
    expiry = typed_data['message']['expiry']
    print(f"  [OK] Typed data generated. Expiry: {expiry}")
    print()
    
    # Create a test account
    print("Step 2: Creating test wallet...")
    test_account = Account.create()
    print(f"  [OK] Test wallet created: {test_account.address}")
    print()
    
    # Sign it (simulating frontend)
    print("Step 3: Signing typed data (simulating frontend ethers.js)...")
    signable_message = encode_typed_data(
        full_message=typed_data
    )
    signature = test_account.sign_message(signable_message)
    print(f"  [OK] Signature generated: {signature.signature.hex()[:66]}...")
    print()
    
    # Verify it (simulating backend)
    print("Step 4: Verifying signature (simulating backend /submit endpoint)...")
    is_valid = signature_service.verify_signature(
        chain_id=chain_id,
        plan_id_hex=plan_id_hex,
        plan_hash_hex=plan_hash_hex,
        nonce=nonce,
        expiry=expiry,
        signature=signature.signature.hex(),
        user_address=test_account.address
    )
    
    print("="*70)
    if is_valid:
        print("[OK] TEST PASSED: Signature verification successful!")
        print("[OK] EIP-712 hashes are consistent between frontend and backend")
        print("="*70)
        return True
    else:
        print("[ERROR] TEST FAILED: Signature verification failed!")
        print("[ERROR] EIP-712 hashes don't match between frontend and backend")
        print("="*70)
        return False

if __name__ == "__main__":
    try:
        success = test_eip712_hash_consistency()
        sys.exit(0 if success else 1)
    except Exception as e:
        print(f"\n[ERROR] TEST CRASHED: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
