# Generated by Django 5.2.8 on 2025-11-05 19:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_wallet', models.CharField(max_length=42)),
                ('input_text', models.TextField(blank=True, null=True)),
                ('intent_json', models.JSONField()),
                ('status', models.CharField(choices=[('parsed', 'Parsed'), ('planned', 'Planned'), ('simulated', 'Simulated'), ('signed', 'Signed'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed'), ('clarify', 'Clarify')], default='parsed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_json', models.JSONField()),
                ('utility_scores', models.JSONField(blank=True, null=True)),
                ('chosen_contract_address', models.CharField(blank=True, max_length=42, null=True)),
                ('simulation_result', models.JSONField(blank=True, null=True)),
                ('ipfs_cid', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('simulated', 'Simulated'), ('approved', 'Approved'), ('executed', 'Executed'), ('failed', 'Failed')], default='ready', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='api_v1.intent')),
            ],
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_hash', models.CharField(blank=True, max_length=66, null=True, unique=True)),
                ('relayer_address', models.CharField(blank=True, max_length=42, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('receipt', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='api_v1.plan')),
            ],
        ),
    ]
