# Generated by Django 5.2.8 on 2025-11-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent',
            name='chain_id',
            field=models.IntegerField(default=1043),
        ),
    ]
