# Generated by Django 5.2.8 on 2025-11-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_intent_chain_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='expiry',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='execution',
            name='nonce',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='execution',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
